% DEMO of curve mpr and straight mpr views of Crohns patient.
% Yechiel Lamash, 2017
%
% read 3d image and centerline
load V;load meta;% loaded using nrrdread.m
load cent; % generated by centerlineExtractor2.m

V=gen_isotropic_volume(V,meta);

% view mpr:
curved_mpr(V,cent');
straight_mpr(V,cent);